source: docs
encoding: utf-8
repository: MisterGlass/ghpages-vscode
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      title: ""

# plugins:
#   - jekyll-github-metadata
#   - jekyll-mentions
#   - jekyll-redirect-from
#   - jekyll-sitemap
#   - jemoji
