version: '3'
services:
  jekyll:
    image: jekyll/builder
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/srv/jekyll
    tty: true
